package com.kevinfreyap.domain.error

enum class ErrorMessage {
    TRANSACTION_NAME_REQUIRED,
    TRANSACTION_AMOUNT_ZERO,
    TRANSACTION_AMOUNT_FROM_GREATER_THAN_TO,
    TRANSACTION_CURRENCY_NOT_VALID,
    TRANSACTION_CATEGORY_NOT_SELECTED,
    TRANSACTION_NOTES_TOO_LONG,
    AUTHENTICATION_EMAIL_BLANK,
    AUTHENTICATION_EMAIL_WRONG_FORMAT,
    AUTHENTICATION_EMAIL_USED,
    AUTHENTICATION_PASSWORD_BLANK,
    AUTHENTICATION_PASSWORD_TOO_SHORT,
    AUTHENTICATION_PASSWORD_WRONG,
    AUTHENTICATION_CONFIRM_PASSWORD_BLANK,
    AUTHENTICATION_CONFIRM_PASSWORD_NOT_MATCH
}