package com.kevinfreyap.domain.error

enum class Field {
    TRANSACTION_NAME,
    TRANSACTION_AMOUNT,
    TRANSACTION_CATEGORY,
    AUTHENTICATION_EMAIL,
    AUTHENTICATION_PASSWORD,
    AUTHENTICATION_CONFIRM_PASSWORD
}