package com.kevinfreyap.domain.error

enum class Field {
    TRANSACTION_NAME,
    TRANSACTION_AMOUNT,
    TRANSACTION_CATEGORY,
    TRANSACTION_NOTES,
    AUTHENTICATION_EMAIL,
    AUTHENTICATION_PASSWORD,
    AUTHENTICATION_CONFIRM_PASSWORD,
    AUTHENTICATION_CHANGE_PASSWORD_EMAIL,
    USERNAME,
    IMAGE_URL,
    AUTHENTICATION_NEW_PASSWORD
}